### PR TITLE
Integrated first draft of survey response design

### PR DESCRIPTION
**Pull request by dhilton**
**What**

A first pass of integration of survey response designs, need to sort out thanks.html
next and mobile test this, but looking in a good state, ready for test.

**How to test**
1. Deploy a new environement using eq-terraform, editing the branch to be deployed to `digeq-80-admin-first-draft`
2. Check that a rendered questionnaire is presented correctly.

**Who can test**

Anyone but @dhilton

### CODE REVIEW

**Comment by alexmorris** [comment]
Just as an FYI the mobile styles are a little borked. I will fix over the weekend and we can do a hotfix monday morning

**Comment by alexmorris** [comment]
Also - this is very, very much WIP. Need to reconsider usage of ONS style guide for presentation for starters

**Comment by warrenbailey** [comment]
There's a few minor issues with text alignment and the ONS logo is in the wrong place. However it looks a lot better than the bare bones version, so I suggest we merge this and fix later.

screenshot from 2015-10-05 08 38 07

**Comment by warrenbailey** [comment]
:+1:

**Pull request merged**
